### ISSUE TITLE
[CI] add commit_hash to release.yaml

### ISSUE THREAD

**Issue by giuseppeambrosio97** [FocoosAI/focoos#57]
```yaml
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_next_version.outputs.new_tag }}
          name: Release ${{ steps.get_next_version.outputs.new_tag }}
          body: ${{ steps.get_next_version.outputs.changelog }}
          generateReleaseNotes: true
          commit: ${{ steps.commit_step.outputs.commit_sha }}
```

In commit the correct output should be

```yaml
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_next_version.outputs.new_tag }}
          name: Release ${{ steps.get_next_version.outputs.new_tag }}
          body: ${{ steps.get_next_version.outputs.changelog }}
          generateReleaseNotes: true
          commit: ${{ steps.commit_step.outputs.commit_hash }}
```

reference: https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#outputs
